title: Your awesome title
author: GitHub User
email: your-email@domain.com
copyright: © 2019 GitHub User
description: > # this means to ignore newlines until "show_excerpts:"
  코로나 어드민 페이지

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/avatar.jpg

  # generate social links
  social_links:
    twitter: jekyllrb
    github:  jekyll
    medium:  jekyll
    rss: rss
    dribbble: jekyll
    facebook: jekyll
    flickr:   jekyll
    instagram: jekyll
    linkedin: jekyll
    pinterest: jekyll
    youtube_user: jekyll
    youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    telegram: jekyll
    googleplus: +jekyll
    keybase: jekyll

theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag
